webhook:
    port: 8080
    path: /your_API_path
    secret: your_secret_key
scripts:
    scripts_path: /etc/hexo-webhooks-autocd/scripts
    push: deploy.sh
ssl:
    enabled: true
    cert_file: /etc/hexo-webhooks-autocd/cert/fullchain.pem
    key_file: /etc/hexo-webhooks-autocd/cert/privkey.pem