webhook:
    port: 8080
    path: /webhook
    secret: your_secret_key
scripts:
    scripts_path: .
    push: test.sh
ssl:
    enabled: true
    cert_file: cert/fullchain.pem
    key_file: cert/privkey.pem